### ISSUE TITLE
Stream Deck+ Support

### ISSUE THREAD

**Issue by zacgoodwin** [dim-stream-deck/com.dim.streamdeck#2]
Howdy, 

This doesn't seem to support stream deck +. Any idea when that feature will be added?

**Comment by fcannizzaro** [comment]
Yep, it's already supported, I'm waiting for Elgato to update the plugin to update the code on the DIM application (since it breaks old plugins). 

![image](https://user-images.githubusercontent.com/6225939/210440033-aad1303c-cf89-4878-8196-5a22cb529405.png)

I recently bought an SD+! 😄 I'm also thinking about a lot of touch/dial actions!
